=== Himond/jwd-second-task-xml/src/main/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="tariff" type="tns:Tariff" abstract="true"/>
    <element name="internet-tariff" type="tns:internetTariff" substitutionGroup="tns:tariff"/>
    <element name="mobile-tariff" type="tns:mobileTariff" substitutionGroup="tns:tariff"/>

    <complexType name="Tariff">
        <sequence>
            <element name="payroll" type="positiveInteger"/>
            <element name="connection-pay" type="positiveInteger"/>
            <xs:element name="introduction-time" type="xs:date"/>
        </sequence>
    </complexType>

    <complexType name="mobileTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="call-price" type="tns:callPrice"/>
                </sequence>
                <attribute name="tariff-code" type="tns:tariffCode" use="required"/>
                <attribute name="operator-name" use="optional" default="A1">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="A1"/>
                            <enumeration value="MTS"/>
                            <enumeration value="LIFE"/>
                            <enumeration value="BEELINE"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="internetTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="internet-traffic" type="positiveInteger"/>
                    <element name="transmission-speed" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="callPrice">
        <sequence>
            <element name="tariffication" type="positiveInteger"/>
            <element name="within-the-network" type="double"/>
            <element name="offline" type="double"/>
            <element name="city-network" type="double"/>
        </sequence>
    </complexType>

    <simpleType name="tariffCode">
        <restriction base="ID">
            <pattern value="[a-z]\d{4,8}"/>
        </restriction>
    </simpleType>


</schema>

=== Himond/jwd-second-task-xml/src/test/resources/invalidtest.xml
<?xml version="1.0" encoding="UTF-8"?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/tariffs"
          xsi:schemaLocation="http://www.example.сom/tariffs tariffs.xsd">

    <mobile-tariff tariff-code="a1254884">
        <payroll>25</payroll>
        <introduction-time>2020-03-23</introduction-time>
        <call-price>
            <tariffication>20</tariffication>
            <within-the-network>0.1</within-the-network>
            <offline>0.2</offline>
            <city-network>0.5</city-network>
        </call-price>
    </mobile-tariff>

    <mobile-tariff operator-name="LIFE">
        <payroll>30</payroll>
        <connection-pay>1</connection-pay>
        <introduction-time>2021-02-12</introduction-time>
        <call-price>
            <tariffication>60</tariffication>
            <within-the-network>0.5</within-the-network>
            <offline>1.5</offline>
            <city-network>2.1</city-network>
        </call-price>
    </mobile-tariff>


</tariffs>

=== Himond/jwd-second-task-xml/src/test/resources/validtest.xml
<?xml version="1.0" encoding="UTF-8"?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/tariffs"
          xsi:schemaLocation="http://www.example.сom/tariffs tariffs.xsd">

    <mobile-tariff tariff-code="a12345" operator-name="BEELINE">
        <payroll>30</payroll>
        <connection-pay>10</connection-pay>
        <introduction-time>2020-03-23</introduction-time>
        <call-price>
            <tariffication>20</tariffication>
            <within-the-network>0.12</within-the-network>
            <offline>0.15</offline>
            <city-network>0.59</city-network>
        </call-price>
    </mobile-tariff>

    <internet-tariff>
        <payroll>100</payroll>
        <connection-pay>50</connection-pay>
        <introduction-time>2021-02-11</introduction-time>
        <internet-traffic>5000</internet-traffic>
        <transmission-speed>12500</transmission-speed>
    </internet-tariff>

</tariffs>
